# This file is automatically generated by RSpec and can be used to configure RSpec

RSpec.configure do |config|
  # Use color in STDOUT
  config.color = true

  # Use the specified formatter
  config.formatter = :documentation

  # Configure RSpec to only run tests in the tests/ directory
  config.default_path = 'tests'

  # Configure warnings
  config.warnings = false

  # Run specs in random order to surface order dependencies
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option
  Kernel.srand config.seed

  # Print the random seed for debugging
  config.before(:suite) do
    puts "Running tests with seed: #{config.seed}"
  end
end
